export const ENTITY = {
  USERS: 'users',
  SCHOOLS: 'schools',
  PROGRAMS: 'programs',
  DISTRICTS: 'cities',
  CITIES: 'districts',
  SCHOOL: 'school',
  CLASSES: 'classes',
  SCHEDULES: 'schedules',
  HOMEWORK: 'homework',
  LESSONS: 'lessons',
  LESSON_CONTENTS: 'lesson-contents',
  ATTENDEES: 'attendees',
  LESSON: 'lesson',
  DASHBOARDS: 'dashboards',
  REPORTS: 'reports',
  REPORT: 'report',
  ATTEMPTED: 'attempted',
  MATERIALS: 'materials',
  SKILLS: 'skills',
  PROFILES: 'profiles',
  TRANSFER: 'transfer',
  AUTH: 'auth',
  ROLES: 'roles',
  LESSON_MODULES: 'lesson-modules',
  PAYMENT: 'payment',
};
